apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: gcs-secret
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm               # name of the SecretStore (or kind specified)
  target:
    name: gcs-creds  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: gcs.client.default.credentials_file  # name of the GCPSM secret key
    remoteRef:
      key: pebrc-storage 
